image: ubuntu

services:
  - name: microsoft/mssql-server-linux
    alias: mssql

variables:
  # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
  ACCEPT_EULA: Y
  sa_password: yourStrong(!)Password

before_script:
    - apt-get update 
    - apt-get install ant -y 
    - apt-get install wget -y &>/dev/null
    - export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
    - export JAVA_OPTS=-Dfile.encoding=UTF8
   #  - wget http://apache.crihan.fr/dist/tomcat/tomcat-8/v8.5.39/bin/apache-tomcat-8.5.39.tar.gz &>/dev/null
   #  - mkdir tomcat8
   #  - cd tomcat8
   #  - mv ../apache-tomcat-8.5.39.tar.gz .
   #  - tar xvzf apache-tomcat-8.5.39.tar.gz &>/dev/null
   #  - export CATALINA_HOME=$(pwd)/apache-tomcat-8.5.39
   #  - export PATH=$PATH:$CATALINA_HOME
    - cd Encheres
stages:
  - build

builds:
  stage: build
  script:
    - ant -buildfile build-CI.xml
  artifacts:
    paths:
    - Encheres/dist/*.jar
    reports:
      junit: Encheres/testreports/*.xml

