image: webratio/ant

before_script:
    - export JAVA_OPTS=-Dfile.encoding=UTF8
    - cd Encheres

stages:
  - build
  - test

builds:
  stage: build
  script:
    - ant compile

tests:
  stage: test
  script:
    - ant test
