image: ubuntu

#services:
 # - name: microsoft/mssql-server-linux
 #   alias: mssql

#variables:
  # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
  #ACCEPT_EULA: Y
  #SA_PASSWORD: $GLOBAL_PASSWORD

before_script:
    - apt-get update &>/dev/null
    - apt-get install -y gnupg2 &>/dev/null
    - apt-get install wget -y &>/dev/null
    - wget -qO - https://packages.microsoft.com/keys/microsoft.asc | iconv -f windows-1251 |  apt-key add -
    - wget -qO - https://packages.microsoft.com/config/ubuntu/16.04/prod.list | iconv -f windows-1251 | tee /etc/apt/sources.list.d/msprod.list
    - apt-get update &>/dev/null
    - apt-get install ant -y &>/dev/null
    - export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
    - export JAVA_OPTS=-Dfile.encoding=UTF8
    - source ~/.bashrc
    - cd Encheres
    - sed -i -e 's/SQLPASSWORD/'"$GLOBAL_PASSWORD"'/g' build-CI.xml
stages:
  - build

build:
  stage: build
  script:
    - ant -buildfile build-CI.xml
  artifacts:
    paths:
    - Encheres/dist/*.war
    reports:
      junit: Encheres/testreports/*.xml

