image: ubuntu

before_script:
    - apt-get update
    - apt-get install ant -y
    - export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
    - export JAVA_OPTS=-Dfile.encoding=UTF8
    - wget http://apache.crihan.fr/dist/tomcat/tomcat-8/v8.5.39/bin/apache-tomcat-8.5.39.tar.gz
    - mkdir tomcat8
    - cd tomcat8
    - mv ../apache-tomcat-8.5.39.tar.gz .
    - tar xvzf apache-tomcat-8.5.39.tar.gz &>/dev/null
    - export CATALINA_HOME=$(pwd)/apache-tomcat-8.5.39
    - export PATH=$PATH:$CATALINA_HOME
    - ls $CATALINA_HOME/lib
    - cd ../Encheres

stages:
  - build
  - test

builds:
  stage: build
  script:
    - ant -buildfile build-CI.xml compile

tests:
  stage: test
  script:
    - ant -buildfile build-CI.xml test
