image: ubuntu

services:
  - name: microsoft/mssql-server-linux
    alias: mssql

variables:
  # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
  ACCEPT_EULA: Y
  SA_PASSWORD: yourStrong(!)Password

before_script:
    - apt-get update &>/dev/null
    - apt-get install wget -y &>/dev/null
    - wget -qO - https://packages.microsoft.com/keys/microsoft.asc | iconv -f windows-1251 |  apt-key add -
    - wget -qO - https://packages.microsoft.com/config/ubuntu/16.04/prod.list | iconv -f windows-1251 | tee /etc/apt/sources.list.d/msprod.list
    - apt-get update &>/dev/null
    - apt-get install ant -y &>/dev/null
    - apt-get install -y gnupg2 &>/dev/null
    - apt-get install curl -y &>/dev/null 
    - apt-get install wget -y &>/dev/null
    - export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
    - export JAVA_OPTS=-Dfile.encoding=UTF8
    - apt-get install -y mssql-tools unixodbc-dev
    - echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
    - echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
    - source ~/.bashrc
    - cd Encheres
    - ls /opt/mssql-tools/bin/sqlcmd*
    - ln -sfn /opt/mssql-tools/bin/sqlcmd /usr/bin/sqlcmd
    - sqlcmd -S mssql -U sa -P yourStrong(!)Password -i script/create_bd_trocencheres.sql
stages:
  - build

builds:
  stage: build
  script:
    - ant -buildfile build-CI.xml
  artifacts:
    paths:
    - Encheres/dist/*.jar
    reports:
      junit: Encheres/testreports/*.xml

