image: openjdk:8-jdk

before_script:
    - wget http://miroir.univ-lorraine.fr/apache//ant/binaries/apache-ant-1.10.5-bin.tar.gz
    - tar xvzf apache-ant-1.10.5-bin.tar.gz
    - export ANT_OPTS="-Xmx256M"
    - pwd
    - export ANT_HOME=apache-ant-1.10.5-bin
    - export PATH=${ANT_HOME}/bin:${JAVA_HOME}/bin:${PATH}

stages:
  - build
  - test

builds:
  stage: build
  script:
    - ant compile

tests:
  stage: test
  script:
    - ant test
